# MickTrace Production Logging Configuration

# Global Settings
global:
  service_name: order-processing-service
  environment: production
  version: 1.0.0
  default_level: INFO

# Handlers Configuration
handlers:
  console:
    type: console
    level: INFO
    formatter: json
    filters:
      - level_filter
      - correlation_filter

  file_main:
    type: file
    level: DEBUG
    filename: logs/service.log
    max_bytes: 10485760  # 10MB
    backup_count: 5
    formatter: json
    filters:
      - correlation_filter

  file_error:
    type: file
    level: ERROR
    filename: logs/error.log
    max_bytes: 5242880  # 5MB
    backup_count: 10
    formatter: json
    filters:
      - error_filter
      - correlation_filter

  async_batch:
    type: file
    level: INFO
    filename: logs/batch_processing.log
    max_bytes: 20971520  # 20MB
    backup_count: 3
    formatter: json
    filters:
      - batch_filter

# Formatters Configuration
formatters:
  json:
    type: json
    include_timestamp: true
    include_level: true
    include_logger_name: true
    include_thread_info: true
    include_process_info: true

  logfmt:
    type: logfmt
    include_timestamp: true
    time_format: iso8601

# Filters Configuration
filters:
  level_filter:
    type: level
    min_level: INFO
    max_level: CRITICAL

  correlation_filter:
    type: callable
    function: has_correlation_id

  error_filter:
    type: level
    min_level: ERROR

  batch_filter:
    type: callable
    function: is_batch_operation

# Context Configuration
context:
  static:
    service: order-processing-service
    environment: production
    version: 1.0.0

  dynamic:
    request_id: true
    correlation_id: true
    user_id: true
    trace_id: true

# Performance Configuration
performance:
  async_mode: true
  buffer_size: 1000
  flush_interval: 1.0  # seconds
  worker_threads: 2

# Monitoring Configuration
monitoring:
  enable_metrics: true
  statsd_host: localhost
  statsd_port: 8125
  prefix: micktrace.logs

# Error Handling
error_handling:
  max_retries: 3
  retry_interval: 1.0
  ignore_errors:
    - ConnectionError
    - TimeoutError